In [1]:
import xarray as xr
import pandas as pd
import glob
import os
import math

import numpy as np
import re
from joblib import Parallel, delayed
from pathlib import Path
import matplotlib.pyplot as plt
import alphashape
from itertools import combinations
from collections import defaultdict, deque
from concurrent.futures import ThreadPoolExecutor

from concurrent.futures import ProcessPoolExecutor, as_completed


from shapely import points, contains
import random

In [2]:
working_dir = '/glade/work/qingyuany/repo_data/'
case_name = "test"

ppe_para = pd.read_csv("/glade/work/qingyuany/repo_data/spatialtuning/paras_v4.csv", index_col=0)

In [302]:
para_seq = list(test_case.grouped_hulls.keys())[:15]
check = orchestrate_test(para_seq, test_case.p_emu, test_case.tf_masks,  test_case.para_nm, test_case.grouped_hulls, test_case.paras_vars, n_pts=  10000, n_threshold = 100,sample_threshold = 10**5, max_workers = 31)

## Add random seed generator for the batch sampling method

Running ('clubb_C8', 'microp_aero_wsub_min')
There is overlap for ('clubb_C8', 'microp_aero_wsub_min'). Proceed to the next parameter pair
======================================================================
Running ('clubb_C8', 'microp_aero_wsubi_scale')
There is overlap for ('clubb_C8', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('dust_emis_fact', 'microp_aero_wsubi_scale')
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 16116
	 	Running test to see if ('dust_emis_fact', 'microp_aero_wsubi_scale') could be break down and lead to non-overlapping
Try 8 combinations
Try one of the combinations
Try one of the combinations
Try one of the combinations
Try one of the combinations
Try one of the combinations
Try one of the combinations
Try one of the combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['FLUT_zonal_50to55']
======================================================================
Running ('clubb_c14', 'microp_aero_wsubi_scale')
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 243
	 	Running test to see if ('clubb_c14', 'microp_aero_wsubi_scale') could be break down and lead to non-overlapping
Try 8 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['FLUT_zonal_-50to-45']
======================================================================
Running ('clubb_c2rt', 'zmconv_dmpdz')
There is overlap for ('clubb_c2rt', 'zmconv_dmpdz'). Proceed to the next parameter pair
======================================================================
Running ('clubb_C8', 'cldfrc_dp1')
There is overlap for ('clubb_C8', 'cldfrc_dp1'). Proceed to the next parameter pair
======================================================================
Running ('micro_mg_berg_eff_factor', 'microp_aero_wsubi_scale')
There is overlap for ('micro_mg_berg_eff_factor', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('zmconv_capelmt', 'seasalt_emis_scale')
There is overlap for ('zmconv_capelmt', 'seasalt_emis_scale'). Proceed to the next parameter pair
======================================================================
Running ('clubb_c14', 'clubb_c2rt')
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 111
	 	Running test to see if ('clubb_c14', 'clubb_c2rt') could be break down and lead to non-overlapping
Try 2 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['TMQ_zonal_-55to-50']
======================================================================
Running ('clubb_c2rt', 'microp_aero_wsubi_scale')
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 100
	 	Running test to see if ('clubb_c2rt', 'microp_aero_wsubi_scale') could be break down and lead to non-overlapping
Try 2 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['TMQ_zonal_-30to-25']
======================================================================
Running ('micro_mg_berg_eff_factor', 'clubb_c2rt')
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 33
	 	Running test to see if ('micro_mg_berg_eff_factor', 'clubb_c2rt') could be break down and lead to non-overlapping
Try 2 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['TMQ_zonal_-40to-35']
======================================================================
Running ('clubb_gamma_coef', 'microp_aero_wsubi_scale')
There is overlap for ('clubb_gamma_coef', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('microp_aero_wsub_scale', 'microp_aero_wsubi_scale')
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 34
	 	Running test to see if ('microp_aero_wsub_scale', 'microp_aero_wsubi_scale') could be break down and lead to non-overlapping
Try 1 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['FLUT_zonal_-5to0']
======================================================================
Running ('zmconv_ke', 'microp_aero_wsubi_scale')
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 34
	 	Running test to see if ('zmconv_ke', 'microp_aero_wsubi_scale') could be break down and lead to non-overlapping
Try 1 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['FLUT_zonal_-70to-65']
======================================================================
Running ('clubb_C8', 'dust_emis_fact')
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 3
	 	Running test to see if ('clubb_C8', 'dust_emis_fact') could be break down and lead to non-overlapping
Try 1 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['FSNTOA_zonal_40to45']
======================================================================

In [304]:
pts = sample_from_hulls_n(list(check[2].keys())[:15], test_case.para_nm, check[2],n_pts=50000, n_threshold=5000,max_workers=32,sample_threshold=10**8)

In [305]:
pts

,micro_mg_max_nicons,micro_mg_vtrmi_factor,micro_mg_iaccr_factor,micro_mg_berg_eff_factor,micro_mg_accre_enhan_fact,micro_mg_homog_size,micro_mg_dcs,clubb_c1,clubb_C8,clubb_c11,...,zmconv_capelmt,seasalt_emis_scale,dust_emis_fact,sol_factb_interstitial,sol_factic_interstitial,microp_aero_wsub_min,microp_aero_wsubi_min,microp_aero_wsub_scale,microp_aero_wsubi_scale,microp_aero_npccn_scale
0,0.717481,0.655254,0.032446,0.721807,0.757208,0.849285,0.276364,0.272555,0.583480,0.571921,...,0.780427,0.106459,0.625564,0.281432,0.433844,0.289172,0.392828,0.589066,0.468679,0.189211
1,0.399035,0.830557,0.220663,0.888497,0.961610,0.609981,0.925114,0.395975,0.595672,0.385777,...,0.578850,0.259019,0.374189,0.881989,0.411433,0.157830,0.733921,0.752034,0.460149,0.276792
2,0.553574,0.562252,0.600243,0.242353,0.968290,0.301465,0.524629,0.269695,0.608246,0.580905,...,0.690034,0.432872,0.862849,0.736599,0.282618,0.238961,0.701795,0.733696,0.431661,0.241193
3,0.555581,0.510020,0.486798,0.607664,0.638380,0.927395,0.826618,0.350399,0.611472,0.344890,...,0.942610,0.329706,0.727440,0.086536,0.058189,0.177739,0.358373,0.714589,0.446181,0.288866
4,0.491167,0.973625,0.368139,0.725085,0.729030,0.488723,0.533889,0.759983,0.604066,0.015763,...,0.726630,0.494812,0.844292,0.698194,0.375483,0.251221,0.426511,0.330043,0.483440,0.844226
5,0.898249,0.608116,0.507325,0.187974,0.700619,0.027226,0.588590,0.354177,0.610794,0.444314,...,0.525999,0.384473,0.833729,0.921204,0.653013,0.213198,0.586057,0.045564,0.441383,0.920286
6,0.896327,0.311640,0.426715,0.666380,0.213966,0.522828,0.254956,0.462834,0.593111,0.102429,...,0.886427,0.261111,0.662121,0.056258,0.178757,0.182395,0.004037,0.423210,0.448644,0.825951
7,0.434302,0.535087,0.203684,0.652255,0.961858,0.874785,0.704454,0.010999,0.608968,0.972680,...,0.036353,0.923650,0.472970,0.673187,0.595052,0.240083,0.687219,0.192232,0.418909,0.859418
8,0.398885,0.092298,0.454403,0.549675,0.232156,0.303823,0.653249,0.559090,0.596111,0.813882,...,0.943615,0.051201,0.946659,0.653570,0.579307,0.157374,0.657897,0.186015,0.460977,0.780523
9,0.019350,0.533750,0.258118,0.465499,0.184011,0.087092,0.651227,0.291153,0.569422,0.570217,...,0.970122,0.511719,0.600709,0.878121,0.052425,0.128388,0.947833,0.953316,0.488499,0.912207
10,0.230437,0.145217,0.217162,0.675497,0.898407,0.395945,0.907228,0.119636,0.575579,0.754825,...,0.739072,0.300222,0.762846,0.969268,0.299509,0.311534,0.955598,0.865923,0.487141,0.363444
11,0.268212,0.601330,0.721174,0.550930,0.167524,0.114915,0.371517,0.231087,0.605260,0.426288,...,0.509919,0.308396,0.965620,0.615205,0.768307,0.208822,0.944732,0.182576,0.437505,0.861756
12,0.804093,0.968067,0.884144,0.791056,0.058886,0.823598,0.022090,0.619556,0.602111,0.500236,...,0.486511,0.221969,0.488710,0.981531,0.822691,0.189941,0.577679,0.760059,0.443402,0.666057
13,0.100526,0.413188,0.472385,0.329136,0.253705,0.773848,0.592881,0.920010,0.587478,0.250975,...,0.959353,0.454949,0.593190,0.691512,0.527501,0.186549,0.411114,0.486173,0.463875,0.993360
14,0.000810,0.495126,0.371823,0.524426,0.962420,0.315186,0.443626,0.039320,0.587661,0.391619,...,0.259161,0.853728,0.709926,0.555209,0.983582,0.277641,0.805279,0.361617,0.455803,0.150297
15,0.153081,0.985856,0.011343,0.438356,0.438747,0.541638,0.103542,0.610833,0.602939,0.470909,...,0.730149,0.109650,0.640560,0.033332,0.739188,0.258933,0.739098,0.564579,0.428672,0.665543
16,0.692596,0.735045,0.697326,0.978973,0.692773,0.041378,0.347088,0.575921,0.575556,0.510587,...,0.800295,0.201820,0.784056,0.181994,0.265533,0.278161,0.096995,0.017599,0.491912,0.175053
17,0.387358,0.825475,0.403425,0.925561,0.762784,0.148548,0.159202,0.380508,0.602450,0.045591,...,0.986895,0.119785,0.990705,0.754899,0.648131,0.246383,0.977625,0.650135,0.443417,0.904974
18,0.684932,0.627645,0.401487,0.033457,0.891169,0.128974,0.091512,0.997021,0.613566,0.631992,...,0.783732,0.482345,0.471017,0.759380,0.527791,0.218839,0.284430,0.996279,0.452050,0.976811
19,0.526696,0.293807,0.830376,0.107918,0.134923,0.988624,0.838213,0.203198,0.608817,0.527774,...,0.628634,0.606609,0.892133,0.498401,0.983467,0.218669,0.504781,0.691088,0.456965,0.836132
20,0.277144,0.420199,0.595423,0.059000,0.467327,0.523174,0.955299,0.743548,0.608257,0.449303,...,0.409294,0.683286,0.431212,0.635965,0.155970,0.194114,0.501511,0.933351,0.418631,0.198231
21,0.823137,0.220955,0.919575,0.429333,0.940124,0.188867,0.630491,0.722873,0.609471,0.420742,...,0.078005,0.783254,0.721991,0.782757,0.322311,0.196705,0.337424,0.822443,0.477255,0.696966
22,0.068592,0.583948,0.737958,0.639893,0.673797,0.157185,0.420186,0.071774,0.600181,0.698587,...,0.758015,0.377895,0.400507,0.643922,0.856532,0.167625,0.236500,0.072684,0.491999,0.032693
23,0.081226,0.881790,0.496997,0.617622,0.303995,0.676065,0.801490,0.113942,0.558257,0.041639,...,0.771538,0.111219,0.782884,0.245372,0.232867,0.251882,0.205246,0.570552,0.506855,0.673119
24,0.453614,0.568629,0.122710,0.189075,0.589532,0.889102,0.326948,0.843659,0.616909,0.268434,...,0.077199,0.852255,0.488701,0.003907,0.608674,0.205909,0.103735,0.029012,0.479451,0.613702
25,0.743080,0.479109,0.568170,0.720395,0.285716,0.153723,0.340241,0.455967,0.605681,0.026806,...,0.014296,0.858454,0.414516,0.922304,0.615797,0.224650,0.421429,0.394778,0.433224,0.376117
26,0.732347,0.369730,0.600611,0.382725,0.187400,0.725793,0.346343,0.239816,0.580390,0.353360,...,0.935247,0.148474,0.805988,0.768946,0.651055,0.194953,0.627479,0.616291,0.471742,0.734211
27,0.003659,0.583029,0.738960,0.517139,0.058479,0.229060,0.672684,0.542015,0.613317,0.050962,...,0.237840,0.975365,0.763624,0.125400,0.789349,0.228883,0.888599,0.655103,0.409608,0.438589
28,0.278618,0.878022,0.958818,0.336502,0.448243,0.940552,0.885863,0.855069,0.590325,0.168760,...,0.535927,0.043259,0.496611,0.981285,0.634528,0.184327,0.909758,0.745512,0.472951,0.016264

In [306]:
pts = sample_from_hulls_n(list(check[2].keys())[:5], test_case.para_nm, check[2],n_pts=50000, n_threshold=5000,sample_threshold=10**8,max_workers=32)
pts.head()

,micro_mg_max_nicons,micro_mg_vtrmi_factor,micro_mg_iaccr_factor,micro_mg_berg_eff_factor,micro_mg_accre_enhan_fact,micro_mg_homog_size,micro_mg_dcs,clubb_c1,clubb_C8,clubb_c11,...,zmconv_capelmt,seasalt_emis_scale,dust_emis_fact,sol_factb_interstitial,sol_factic_interstitial,microp_aero_wsub_min,microp_aero_wsubi_min,microp_aero_wsub_scale,microp_aero_wsubi_scale,microp_aero_npccn_scale
0,0.458174,0.467109,0.294542,0.804598,0.396397,0.239799,0.341688,0.918578,0.553233,0.775874,...,0.381315,0.579864,0.671861,0.420453,0.208277,0.215476,0.489183,0.985240,0.537921,0.970825
1,0.845069,0.684898,0.043103,0.267495,0.713074,0.695765,0.817098,0.015312,0.580106,0.525918,...,0.416536,0.297453,0.838567,0.842234,0.962809,0.275011,0.054637,0.467455,0.488970,0.888280
2,0.756753,0.178489,0.977610,0.286773,0.721442,0.012818,0.622762,0.751775,0.541287,0.003133,...,0.971410,0.080117,0.530461,0.896090,0.827983,0.325359,0.115717,0.320298,0.550336,0.698222
3,0.644512,0.532384,0.486430,0.470606,0.240153,0.111987,0.054266,0.171817,0.578062,0.202516,...,0.722983,0.173609,0.420818,0.865941,0.689564,0.141134,0.197220,0.214059,0.490371,0.908779
4,0.217523,0.240875,0.501144,0.834641,0.861651,0.674814,0.486635,0.339514,0.606150,0.145758,...,0.031980,0.398492,0.737128,0.933461,0.439146,0.227624,0.081498,0.165688,0.467637,0.018043

In [297]:
test_case = HistoryMatching(working_dir, case_name)
test_case.drop_by_name(["TGCLDLWP", "CLDTOT"])
test_case.drop_by_n_survive(n_survive = 100000)
test_case.update_meta()

In [298]:
test_case.group_para_climatology()
summary2d = test_case.shuffle_vars()

clubb_C8                                 and microp_aero_wsub_min                    :   314967
clubb_C8                                 and microp_aero_wsubi_scale                 :    48436
dust_emis_fact                           and microp_aero_wsubi_scale                 :        0
clubb_c14                                and microp_aero_wsubi_scale                 :   176779
micro_mg_berg_eff_factor                 and microp_aero_wsubi_scale                 :        0
clubb_c2rt                               and zmconv_dmpdz                            :   869194
clubb_c2rt                               and microp_aero_wsubi_scale                 :        0
clubb_C8                                 and zmconv_capelmt                          :        0
clubb_C8                                 and cldfrc_dp1                              :   684794
zmconv_capelmt                           and seasalt_emis_scale                      :   548406
clubb_c14                                and clubb_c2rt                              :   205458
micro_mg_berg_eff_factor                 and clubb_c2rt                              :   492079
clubb_gamma_coef                         and microp_aero_wsubi_scale                 :   876301
microp_aero_wsub_scale                   and microp_aero_wsubi_scale                 :   835374
zmconv_ke                                and microp_aero_wsubi_scale                 :   148773
clubb_C8                                 and dust_emis_fact                          :   972809
clubb_C8                                 and clubb_c2rt                              :   797238
cldfrc_dp1                               and microp_aero_wsubi_scale                 :   539706
clubb_C8                                 and microp_aero_wsub_scale                  :   104158
clubb_C8                                 and seasalt_emis_scale                      :   800616
clubb_c1                                 and microp_aero_wsubi_scale                 :   898663
cldfrc_dp1                               and cldfrc_dp2                              :   761184
There are 4 groups that have no overlapping within own groups

In [299]:
no_overlap_2d_vars = ["FLUT_zonal_55to60", 'LWCF_zonal_-70to-65', 'FLUT_zonal_-60to-55', 
                      'FLUT_zonal_-55to-50', 'FLUT_zonal_-65to-60', 'SWCF_zonal_-60to-55', 
                      'SWCF_zonal_-55to-50', 'LWCF_zonal_70to75', 'LWCF_zonal_65to70', 'LWCF_zonal_30to35']

In [300]:
test_case.drop_no_overlap2d_vars(no_overlap_2d_vars)
test_case.group_para_climatology()
summary2d = test_case.shuffle_vars()

clubb_C8                                 and microp_aero_wsub_min                    :   314967
clubb_C8                                 and microp_aero_wsubi_scale                 :    48436
dust_emis_fact                           and microp_aero_wsubi_scale                 :    70638
clubb_c14                                and microp_aero_wsubi_scale                 :   176779
clubb_c2rt                               and zmconv_dmpdz                            :   869194
clubb_C8                                 and cldfrc_dp1                              :   684794
micro_mg_berg_eff_factor                 and microp_aero_wsubi_scale                 :   813089
zmconv_capelmt                           and seasalt_emis_scale                      :   548406
clubb_c14                                and clubb_c2rt                              :   205458
clubb_c2rt                               and microp_aero_wsubi_scale                 :   126587
micro_mg_berg_eff_factor                 and clubb_c2rt                              :   492079
clubb_gamma_coef                         and microp_aero_wsubi_scale                 :   876301
microp_aero_wsub_scale                   and microp_aero_wsubi_scale                 :   835374
zmconv_ke                                and microp_aero_wsubi_scale                 :   148773
clubb_C8                                 and dust_emis_fact                          :   972809
clubb_C8                                 and clubb_c2rt                              :   797238
cldfrc_dp1                               and microp_aero_wsubi_scale                 :   539706
clubb_C8                                 and zmconv_capelmt                          :   147581
clubb_C8                                 and microp_aero_wsub_scale                  :   104158
clubb_C8                                 and seasalt_emis_scale                      :   800616
clubb_c1                                 and microp_aero_wsubi_scale                 :   898663
cldfrc_dp1                               and cldfrc_dp2                              :   761184
There are 0 groups that have no overlapping within own groups

In [301]:
test_case.build_hulls()