In [37]:
import xarray as xr
import pandas as pd
import glob
import os
import math

import numpy as np
import re
from joblib import Parallel, delayed
from pathlib import Path
import matplotlib.pyplot as plt
import alphashape
from itertools import combinations
from collections import defaultdict, deque
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import ProcessPoolExecutor, as_completed


from shapely import points, contains
import random

In [5]:
from funs.hm_class import (
    meta_one_hot_shot,
    EmulatedDataStorage,
    HistoryMatching)

In [38]:
from funs.sampling_functions import *

In [6]:
working_dir = '/glade/work/qingyuany/repo_data/'
case_name = "test"

ppe_para = pd.read_csv("/glade/work/qingyuany/repo_data/spatialtuning/paras_v4.csv", index_col=0)

In [25]:
test_case = HistoryMatching(working_dir, case_name, ppe_para)
test_case.drop_by_name(["TGCLDLWP", "CLDTOT"])
test_case.drop_by_n_survive(n_survive = 100000)
test_case.update_meta()

In [26]:
test_case.group_para_climatology()
summary2d = test_case.shuffle_vars()

clubb_C8                                 and microp_aero_wsub_min                    :   314439
clubb_C8                                 and microp_aero_wsubi_scale                 :    48837
dust_emis_fact                           and microp_aero_wsubi_scale                 :        0
clubb_c14                                and microp_aero_wsubi_scale                 :   176541
micro_mg_berg_eff_factor                 and microp_aero_wsubi_scale                 :        0
clubb_c2rt                               and zmconv_dmpdz                            :   869608
clubb_c2rt                               and microp_aero_wsubi_scale                 :        0
clubb_C8                                 and zmconv_capelmt                          :        0
clubb_C8                                 and cldfrc_dp1                              :   684126
zmconv_capelmt                           and seasalt_emis_scale                      :   548846
clubb_c14                                and clubb_c2rt                              :   205535
clubb_gamma_coef                         and microp_aero_wsubi_scale                 :   876332
microp_aero_wsub_scale                   and microp_aero_wsubi_scale                 :   835114
zmconv_ke                                and microp_aero_wsubi_scale                 :   148336
clubb_C8                                 and dust_emis_fact                          :   972704
micro_mg_berg_eff_factor                 and clubb_c2rt                              :   540558
clubb_C8                                 and clubb_c2rt                              :   797121
cldfrc_dp1                               and microp_aero_wsubi_scale                 :   539147
clubb_C8                                 and microp_aero_wsub_scale                  :   103856
clubb_C8                                 and seasalt_emis_scale                      :   800387
clubb_c1                                 and microp_aero_wsubi_scale                 :   898952
cldfrc_dp1                               and cldfrc_dp2                              :   761866
There are 4 groups that have no overlapping within own groups

In [27]:
summary2d

{('dust_emis_fact',
  'microp_aero_wsubi_scale'):                  var1               var2   count
 22  LWCF_zonal_30to35  FLUT_zonal_55to60       0
 46  FLUT_zonal_55to60  LWCF_zonal_35to40       0
 10  FLUT_zonal_50to55  LWCF_zonal_30to35      73
 29  LWCF_zonal_40to45  FLUT_zonal_55to60   17637
 16  FLUT_zonal_50to55  LWCF_zonal_35to40   70312
 11  FLUT_zonal_50to55  LWCF_zonal_40to45   97515
 14  FLUT_zonal_50to55  FLUT_zonal_55to60  105588
 5   FLUT_zonal_45to50  FLUT_zonal_55to60  105588
 45  FLUT_zonal_55to60  FLUT_zonal_35to40  105588
 40  FLUT_zonal_25to30  FLUT_zonal_55to60  105588
 48  FLUT_zonal_55to60  FLUT_zonal_40to45  105588
 47  FLUT_zonal_55to60  FLUT_zonal_20to25  105588
 35  FLUT_zonal_30to35  FLUT_zonal_55to60  105588
 0   FLUT_zonal_45to50  FLUT_zonal_50to55  185466
 18  FLUT_zonal_50to55  FLUT_zonal_40to45  185466
 12  FLUT_zonal_50to55  FLUT_zonal_30to35  185466
 13  FLUT_zonal_50to55  FLUT_zonal_25to30  185466
 17  FLUT_zonal_50to55  FLUT_zonal_20to25  185466
 15  FLUT_zonal_50to55  FLUT_zonal_35to40  185466
 1   FLUT_zonal_45to50  LWCF_zonal_30to35  186806
 7   FLUT_zonal_45to50  LWCF_zonal_35to40  281860
 2   FLUT_zonal_45to50  LWCF_zonal_40to45  309063
 9   FLUT_zonal_45to50  FLUT_zonal_40to45  397014
 8   FLUT_zonal_45to50  FLUT_zonal_20to25  397014
 3   FLUT_zonal_45to50  FLUT_zonal_30to35  397014
 6   FLUT_zonal_45to50  FLUT_zonal_35to40  397014
 4   FLUT_zonal_45to50  FLUT_zonal_25to30  397014
 25  LWCF_zonal_30to35  FLUT_zonal_20to25  450096
 26  LWCF_zonal_30to35  FLUT_zonal_40to45  497765
 21  LWCF_zonal_30to35  FLUT_zonal_25to30  511194
 52  LWCF_zonal_35to40  FLUT_zonal_20to25  545150
 20  LWCF_zonal_30to35  FLUT_zonal_30to35  549799
 32  LWCF_zonal_40to45  FLUT_zonal_20to25  572353
 53  LWCF_zonal_35to40  FLUT_zonal_40to45  592819
 42  FLUT_zonal_25to30  LWCF_zonal_35to40  606248
 23  LWCF_zonal_30to35  FLUT_zonal_35to40  609988
 54  FLUT_zonal_20to25  FLUT_zonal_40to45  614044
 33  LWCF_zonal_40to45  FLUT_zonal_40to45  620022
 28  LWCF_zonal_40to45  FLUT_zonal_25to30  633451
 37  FLUT_zonal_30to35  LWCF_zonal_35to40  644853
 50  FLUT_zonal_35to40  FLUT_zonal_20to25  654880
 38  FLUT_zonal_30to35  FLUT_zonal_20to25  656801
 43  FLUT_zonal_25to30  FLUT_zonal_20to25  660304
 44  FLUT_zonal_25to30  FLUT_zonal_40to45  664779
 27  LWCF_zonal_40to45  FLUT_zonal_30to35  672056
 49  FLUT_zonal_35to40  LWCF_zonal_35to40  705042
 39  FLUT_zonal_30to35  FLUT_zonal_40to45  707264
 51  FLUT_zonal_35to40  FLUT_zonal_40to45  707973
 34  FLUT_zonal_30to35  FLUT_zonal_25to30  709832
 41  FLUT_zonal_25to30  FLUT_zonal_35to40  712866
 30  LWCF_zonal_40to45  FLUT_zonal_35to40  732245
 36  FLUT_zonal_30to35  FLUT_zonal_35to40  756840
 19  LWCF_zonal_30to35  LWCF_zonal_40to45  789792
 24  LWCF_zonal_30to35  LWCF_zonal_35to40  789792
 31  LWCF_zonal_40to45  LWCF_zonal_35to40  884846,
 ('micro_mg_berg_eff_factor',
  'microp_aero_wsubi_scale'):                    var1                 var2   count
 1   LWCF_zonal_-70to-65  FLUT_zonal_-60to-55       0
 2   LWCF_zonal_-70to-65  FLUT_zonal_-55to-50       0
 4   LWCF_zonal_-70to-65  FLUT_zonal_-65to-60     781
 21  FLUT_zonal_-55to-50  LWCF_zonal_-50to-45   85504
 17  FLUT_zonal_-60to-55  LWCF_zonal_-50to-45  122190
 18  FLUT_zonal_-55to-50  LWCF_zonal_-55to-50  146149
 13  FLUT_zonal_-60to-55  FLUT_zonal_-55to-50  160453
 8   LWCF_zonal_-60to-55  FLUT_zonal_-55to-50  160453
 19  FLUT_zonal_-55to-50  FLUT_zonal_-65to-60  160453
 20  FLUT_zonal_-55to-50  LWCF_zonal_-65to-60  160453
 14  FLUT_zonal_-60to-55  LWCF_zonal_-55to-50  182835
 16  FLUT_zonal_-60to-55  LWCF_zonal_-65to-60  197139
 15  FLUT_zonal_-60to-55  FLUT_zonal_-65to-60  197139
 7   LWCF_zonal_-60to-55  FLUT_zonal_-60to-55  197139
 5   LWCF_zonal_-70to-65  LWCF_zonal_-65to-60  272862
 0   LWCF_zonal_-70to-65  LWCF_zonal_-60to-55  300655
 3   LWCF_zonal_-70to-65  LWCF_zonal_-55to-50  384606
 6   LWCF_zonal_-70to-65  LWCF_zonal_-50to-45  384606
 26  FLUT_zonal_-65to-60  LWCF_zonal_-50to-45  431278
 22  LWCF_zonal_-55to-50  FLUT_zonal_-65to-60  491923
 25  FLUT_zonal_-65to-60  LWCF_zonal_-65to-60  506227
 10  LWCF_zonal_-60to-55  FLUT_zonal_-65to-60  506227
 27  LWCF_zonal_-65to-60  LWCF_zonal_-50to-45  813307
 12  LWCF_zonal_-60to-55  LWCF_zonal_-50to-45  841100
 23  LWCF_zonal_-55to-50  LWCF_zonal_-65to-60  873952
 11  LWCF_zonal_-60to-55  LWCF_zonal_-65to-60  888256
 9   LWCF_zonal_-60to-55  LWCF_zonal_-55to-50  901745
 24  LWCF_zonal_-55to-50  LWCF_zonal_-50to-45  925051,
 ('clubb_c2rt',
  'microp_aero_wsubi_scale'):                  var1                var2   count
 7   LWCF_zonal_70to75  TMQ_zonal_-30to-25       0
 9  TMQ_zonal_-30to-25   LWCF_zonal_65to70    8395
 1  TMQ_zonal_-25to-20   LWCF_zonal_70to75   52185
 5  TMQ_zonal_-20to-15  TMQ_zonal_-30to-25  126593
 2  TMQ_zonal_-25to-20  TMQ_zonal_-30to-25  126593
 3  TMQ_zonal_-25to-20   LWCF_zonal_65to70  271567
 4  TMQ_zonal_-20to-15   LWCF_zonal_70to75  387001
 0  TMQ_zonal_-25to-20  TMQ_zonal_-20to-15  437554
 8   LWCF_zonal_70to75   LWCF_zonal_65to70  534704
 6  TMQ_zonal_-20to-15   LWCF_zonal_65to70  686310,
 ('clubb_C8',
  'zmconv_capelmt'):                   var1                   var2   count
 2  SWCF_zonal_-60to-55  FSNTOA_zonal_-70to-65       0
 4  SWCF_zonal_-55to-50  FSNTOA_zonal_-70to-65       0
 5  SWCF_zonal_-65to-60  FSNTOA_zonal_-70to-65  147426
 3  SWCF_zonal_-55to-50    SWCF_zonal_-65to-60  368448
 1  SWCF_zonal_-60to-55    SWCF_zonal_-65to-60  496682
 0  SWCF_zonal_-60to-55    SWCF_zonal_-55to-50  580320}

In [28]:
no_overlap_2d_vars = ["FLUT_zonal_55to60", 'LWCF_zonal_-70to-65', 'FLUT_zonal_-60to-55', 
                      'FLUT_zonal_-55to-50', 'FLUT_zonal_-65to-60', 'SWCF_zonal_-60to-55', 
                      'SWCF_zonal_-55to-50', 'LWCF_zonal_70to75', 'LWCF_zonal_65to70', 'LWCF_zonal_30to35']

In [29]:
test_case.drop_no_overlap2d_vars(no_overlap_2d_vars)
test_case.group_para_climatology()
summary2d = test_case.shuffle_vars()
summary2d

clubb_C8                                 and microp_aero_wsub_min                    :   314439
clubb_C8                                 and microp_aero_wsubi_scale                 :    48837
dust_emis_fact                           and microp_aero_wsubi_scale                 :    70312
clubb_c14                                and microp_aero_wsubi_scale                 :   176541
clubb_c2rt                               and zmconv_dmpdz                            :   869608
clubb_C8                                 and cldfrc_dp1                              :   684126
micro_mg_berg_eff_factor                 and microp_aero_wsubi_scale                 :   813307
zmconv_capelmt                           and seasalt_emis_scale                      :   548846
clubb_c14                                and clubb_c2rt                              :   205535
clubb_c2rt                               and microp_aero_wsubi_scale                 :   126593
clubb_gamma_coef                         and microp_aero_wsubi_scale                 :   876332
microp_aero_wsub_scale                   and microp_aero_wsubi_scale                 :   835114
zmconv_ke                                and microp_aero_wsubi_scale                 :   148336
clubb_C8                                 and dust_emis_fact                          :   972704
micro_mg_berg_eff_factor                 and clubb_c2rt                              :   540558
clubb_C8                                 and clubb_c2rt                              :   797121
cldfrc_dp1                               and microp_aero_wsubi_scale                 :   539147
clubb_C8                                 and zmconv_capelmt                          :   147426
clubb_C8                                 and microp_aero_wsub_scale                  :   103856
clubb_C8                                 and seasalt_emis_scale                      :   800387
clubb_c1                                 and microp_aero_wsubi_scale                 :   898952
cldfrc_dp1                               and cldfrc_dp2                              :   761866
There are 0 groups that have no overlapping within own groups

{}

In [30]:
test_case.build_hulls()

In [57]:
%run ./funs/sampling_functions.py

In [56]:

para_seq = list(test_case.grouped_hulls.keys())
check = orchestrate_test(para_seq, test_case.p_emu, test_case.tf_masks,  
                         test_case.para_nm, test_case.grouped_hulls, test_case.paras_vars, n_pts=  10000, n_threshold = 100,sample_threshold = 10**5, max_workers = 31)

## Add random seed generator for the batch sampling method

Running ('clubb_C8', 'microp_aero_wsub_min'), the 0th simulation
There is overlap for ('clubb_C8', 'microp_aero_wsub_min'). Proceed to the next parameter pair
======================================================================
Running ('clubb_C8', 'microp_aero_wsubi_scale'), the 1th simulation
There is overlap for ('clubb_C8', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('dust_emis_fact', 'microp_aero_wsubi_scale'), the 2th simulation
There is overlap for ('dust_emis_fact', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('clubb_c14', 'microp_aero_wsubi_scale'), the 3th simulation
There is overlap for ('clubb_c14', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('clubb_c2rt', 'zmconv_dmpdz'), the 4th simulation
There is overlap for ('clubb_c2rt', 'zmconv_dmpdz'). Proceed to the next parameter pair
======================================================================
Running ('clubb_C8', 'cldfrc_dp1'), the 5th simulation
There is overlap for ('clubb_C8', 'cldfrc_dp1'). Proceed to the next parameter pair
======================================================================
Running ('micro_mg_berg_eff_factor', 'microp_aero_wsubi_scale'), the 6th simulation
There is overlap for ('micro_mg_berg_eff_factor', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('zmconv_capelmt', 'seasalt_emis_scale'), the 7th simulation
There is overlap for ('zmconv_capelmt', 'seasalt_emis_scale'). Proceed to the next parameter pair
======================================================================
Running ('clubb_c14', 'clubb_c2rt'), the 8th simulation
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 100
	 	Running test to see if ('clubb_c14', 'clubb_c2rt') could be break down and lead to non-overlapping
Try 1 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['TMQ_zonal_-50to-45']
======================================================================
Running ('clubb_c2rt', 'microp_aero_wsubi_scale'), the 9th simulation
There is overlap for ('clubb_c2rt', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('clubb_C8', 'clubb_c2rt'), the 10th simulation
There is overlap for ('clubb_C8', 'clubb_c2rt'). Proceed to the next parameter pair
======================================================================
Running ('cldfrc_dp1', 'microp_aero_wsubi_scale'), the 11th simulation
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 38
Increase the scheudler ratio to 3
	 	Running test to see if ('cldfrc_dp1', 'microp_aero_wsubi_scale') could be break down and lead to non-overlapping
Try 1 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['LWCF_zonal_5to10']
======================================================================
Running ('clubb_C8', 'zmconv_capelmt'), the 12th simulation
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 100
	 	Running test to see if ('clubb_C8', 'zmconv_capelmt') could be break down and lead to non-overlapping
Try 1 combinations
Try one of the combinations
	 	 	 Found the good variable combo
	 	 	 	 Modify the original hull and variable
	 	 	 	 Drop ['FSNTOA_zonal_-70to-65']
======================================================================
Running ('clubb_C8', 'microp_aero_wsub_scale'), the 13th simulation
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 100
	 	Running test to see if ('clubb_C8', 'microp_aero_wsub_scale') could be break down and lead to non-overlapping
	 	 	 	 ('clubb_C8', 'microp_aero_wsub_scale') is causing trouble and is skipped
======================================================================
Running ('clubb_C8', 'seasalt_emis_scale'), the 14th simulation
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 93
Increase the scheudler ratio to 1
	 	Running test to see if ('clubb_C8', 'seasalt_emis_scale') could be break down and lead to non-overlapping
	 	 	 	 ('clubb_C8', 'seasalt_emis_scale') is causing trouble and is skipped
======================================================================
Running ('clubb_c1', 'microp_aero_wsubi_scale'), the 15th simulation
There is overlap for ('clubb_c1', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('cldfrc_dp1', 'cldfrc_dp2'), the 16th simulation
Find nothing from 100000 pts
Find nothing, try to resolve it by breaking the variables into groups
First sample out_prev that needs greater sample size, which will take long
The size of out_prev is 33
Increase the scheudler ratio to 3
	 	Running test to see if ('cldfrc_dp1', 'cldfrc_dp2') could be break down and lead to non-overlapping
	 	 	 	 ('cldfrc_dp1', 'cldfrc_dp2') is causing trouble and is skipped
======================================================================

In [65]:
pts = sample_from_hulls_n(list(check[2].keys()), test_case.para_nm, check[2],n_pts=50000, n_threshold=5000,sample_threshold=10**8,max_workers=32)

In [68]:
pts.shape

(288, 34)

In [69]:
pts = sample_from_hulls_n(list(check[2].keys()), test_case.para_nm, check[2],n_pts=50000, n_threshold=5000,sample_threshold=10**7,max_workers=32)
pts.head()

,micro_mg_max_nicons,micro_mg_vtrmi_factor,micro_mg_iaccr_factor,micro_mg_berg_eff_factor,micro_mg_accre_enhan_fact,micro_mg_homog_size,micro_mg_dcs,clubb_c1,clubb_C8,clubb_c11,...,zmconv_capelmt,seasalt_emis_scale,dust_emis_fact,sol_factb_interstitial,sol_factic_interstitial,microp_aero_wsub_min,microp_aero_wsubi_min,microp_aero_wsub_scale,microp_aero_wsubi_scale,microp_aero_npccn_scale
0,0.687833,0.475487,0.375043,0.966714,0.230188,0.924725,0.862302,0.377482,0.575610,0.186604,...,0.517826,0.173689,0.589731,0.396087,0.498119,0.277049,0.292490,0.651595,0.486931,0.802644
1,0.679978,0.133725,0.261117,0.408568,0.413566,0.349073,0.113754,0.526057,0.607549,0.610283,...,0.373542,0.566891,0.495673,0.938429,0.863745,0.209416,0.760442,0.921126,0.449913,0.910110
2,0.295174,0.800338,0.888923,0.508629,0.505389,0.281877,0.906215,0.302882,0.605728,0.210867,...,0.303270,0.490199,0.565099,0.065059,0.598309,0.255159,0.485282,0.405149,0.421326,0.801638
3,0.086747,0.791006,0.631928,0.191797,0.549029,0.418240,0.399970,0.954485,0.605317,0.590099,...,0.623613,0.299126,0.964717,0.986853,0.314669,0.221143,0.795685,0.090702,0.479795,0.226156
4,0.020789,0.934962,0.287757,0.362692,0.780511,0.820984,0.615358,0.667610,0.603209,0.356213,...,0.835560,0.162296,0.384560,0.479969,0.264166,0.209310,0.806532,0.908071,0.428055,0.899511

In [71]:
test_case.rescale_para(pts)

,micro_mg_max_nicons,micro_mg_vtrmi_factor,micro_mg_iaccr_factor,micro_mg_berg_eff_factor,micro_mg_accre_enhan_fact,micro_mg_homog_size,micro_mg_dcs,clubb_c1,clubb_C8,clubb_c11,...,zmconv_capelmt,seasalt_emis_scale,dust_emis_fact,sol_factb_interstitial,sol_factic_interstitial,microp_aero_wsub_min,microp_aero_wsubi_min,microp_aero_wsub_scale,microp_aero_wsubi_scale,microp_aero_npccn_scale
0,6.691233e+09,3.573417,0.502099,0.484798,2.429033,0.000184,0.000532,1.004526,3.275324,0.315367,...,95.856539,0.887139,0.625400,0.465668,0.544458,0.141148,0.059019,3.403700,2.816292,2.487344
1,6.617205e+09,2.700464,0.415874,0.273876,4.212354,0.000077,0.000272,1.215775,3.398142,0.567063,...,80.623127,1.627918,0.545455,0.927361,0.864837,0.107824,0.150392,4.508256,2.663328,2.730782
2,2.990718e+09,4.403178,0.891030,0.311689,5.105318,0.000065,0.000547,0.898458,3.391140,0.329781,...,73.203825,1.483433,0.604464,0.183865,0.632249,0.130362,0.096664,2.393746,2.545197,2.485065
3,1.026453e+09,4.379341,0.696523,0.191958,5.529712,0.000090,0.000371,1.824928,3.389560,0.555073,...,107.025473,1.123458,0.944122,0.968585,0.383710,0.113602,0.157274,1.105115,2.786806,1.181449
4,4.048469e+08,4.747045,0.436036,0.256539,7.780841,0.000164,0.000446,1.417040,3.381455,0.416127,...,129.402693,0.865676,0.451014,0.537076,0.339457,0.107771,0.159392,4.454756,2.573005,2.706773
5,5.070947e+09,2.584746,0.758670,0.204150,0.843301,0.000144,0.000248,1.334570,3.431486,0.403200,...,101.788718,1.445415,0.889033,0.867275,0.300830,0.113105,0.144001,3.625667,2.509097,0.987667
6,4.410550e+09,4.232474,0.646339,0.133472,9.871017,0.000197,0.000431,1.186173,3.387692,0.704850,...,82.677263,1.404599,0.457535,0.914541,0.216222,0.112354,0.066107,0.980742,2.569201,2.806208
7,5.098887e+09,3.260828,0.445835,0.201848,5.396054,0.000047,0.000336,1.536284,3.180557,0.360947,...,127.780005,0.658899,0.770232,0.722923,0.391148,0.077827,0.054319,2.262959,2.996576,2.636829
8,1.573850e+09,4.343591,0.337657,0.395844,9.587216,0.000084,0.000554,0.654622,3.281163,0.657421,...,96.774723,1.187022,0.485614,0.280913,0.151842,0.145489,0.165613,3.292910,2.817721,1.064561
9,7.539509e+09,4.044694,0.455450,0.327408,4.502920,0.000177,0.000300,1.545126,3.333930,0.450192,...,99.678296,0.566632,0.875125,0.901096,0.599428,0.120330,0.120287,0.900968,2.667416,1.776001
10,8.553442e+09,4.802954,0.577370,0.415698,0.567280,0.000158,0.000382,1.229142,3.280566,0.467180,...,105.062506,1.429387,0.542788,0.972831,0.542456,0.141664,0.176478,4.197659,2.804394,0.763277
11,2.408311e+09,4.439449,0.771434,0.195997,6.710349,0.000139,0.000520,0.821114,3.281019,0.497856,...,144.495155,1.455702,0.720574,0.610601,0.185245,0.109434,0.029434,3.593086,2.947932,2.357774
12,3.568438e+09,3.038503,0.822505,0.330871,2.669118,0.000133,0.000290,1.645576,3.210185,0.289171,...,76.165748,1.750050,0.774514,0.260412,0.276881,0.090908,0.121172,4.285575,2.901212,1.962956
13,9.083803e+09,4.460781,0.261188,0.207887,3.086390,0.000189,0.000353,1.618913,3.323561,0.468425,...,122.624609,1.321248,0.604217,0.290177,0.648979,0.106767,0.136104,2.511973,2.730887,2.746563
14,4.465343e+08,3.440681,0.757244,0.389579,1.972434,0.000092,0.000554,1.202602,3.309761,0.736909,...,112.155088,0.746803,0.538595,0.628174,0.729480,0.139389,0.153859,2.604522,2.947119,1.133846
15,2.689735e+09,4.577519,0.793508,0.227921,6.790394,0.000182,0.000352,1.128672,3.410268,0.562857,...,116.728449,1.031768,0.921519,0.798075,0.283180,0.122598,0.027507,2.539635,2.497325,0.711484
16,7.103802e+09,4.563141,0.597043,0.268357,1.489829,0.000032,0.000395,1.378969,3.361983,0.679616,...,92.285425,1.136574,0.964494,0.430047,0.306221,0.136142,0.154193,0.934038,2.817531,1.332805
17,6.868782e+09,4.123856,0.266597,0.372776,3.810440,0.000062,0.000461,1.090806,3.330159,0.734161,...,118.815535,1.256173,0.897395,0.688082,0.411069,0.112450,0.079949,1.030867,2.767934,1.688263
18,4.359893e+08,3.686730,0.871472,0.189673,1.060117,0.000120,0.000431,1.158903,3.320410,0.343323,...,145.921390,1.280488,0.618862,0.480584,0.641216,0.111695,0.133642,0.820014,2.699873,1.180525
19,2.211207e+09,2.774291,0.508139,0.139535,1.533784,0.000038,0.000373,1.400372,3.210468,0.607980,...,131.488680,1.293945,0.545631,0.472993,0.967397,0.073187,0.095982,1.947135,2.953307,0.681059
20,8.422827e+09,4.510833,0.602739,0.158359,6.808206,0.000109,0.000483,0.969076,3.425152,0.327644,...,140.104489,0.875890,0.687745,0.555538,0.242509,0.102351,0.041342,4.676189,2.489133,1.041198
21,2.386324e+09,3.397640,0.269117,0.164928,7.630174,0.000037,0.000425,1.328545,3.308435,0.672969,...,96.195026,0.742396,0.713653,0.203358,0.401914,0.090284,0.170124,3.057695,2.864616,0.699981
22,2.415332e+09,4.598428,0.467422,0.363247,4.219973,0.000071,0.000327,0.722511,3.330401,0.561574,...,116.622317,1.540407,0.684103,0.263337,0.474281,0.139227,0.068605,4.385178,2.778994,2.294485
23,3.559345e+09,2.899253,0.283210,0.160950,8.340819,0.000172,0.000430,1.512189,3.423088,0.219540,...,86.500170,1.157757,0.517701,0.781224,0.281215,0.107321,0.032558,1.115121,2.484993,2.104727
24,4.341152e+09,3.498462,0.668653,0.146146,1.302834,0.000133,0.000546,1.497125,3.281117,0.482241,...,74.025459,1.972633,0.529002,0.152162,0.208905,0.137244,0.115380,3.024943,2.883846,1.986827
25,7.690358e+09,4.251516,0.456075,0.134699,3.923000,0.000186,0.000251,0.998747,3.359871,0.419400,...,143.138970,1.045639,0.676920,0.130996,0.453038,0.141227,0.128759,4.209011,2.855647,2.207244
26,8.493029e+09,3.651070,0.464492,0.311825,8.650375,0.000113,0.000493,1.406241,3.414319,0.795355,...,142.414017,1.141484,0.487404,0.368856,0.615979,0.108233,0.092116,3.055798,2.604245,1.795893
27,1.499991e+09,3.553245,0.692526,0.269270,3.580712,0.000154,0.000319,0.908864,3.118652,0.552531,...,88.147426,1.532212,0.704641,0.252529,0.322506,0.085795,0.026057,0.909730,3.026269,1.420452
28,8.792757e+09,2.746921,0.520677,0.380555,9.308184,0.000156,0.000287,1.152165,3.412479,0.551938,...,115.702299,1.261199,0.962150,0.639372,0.252097,0.096185,0.100920,4.266004,2.533363,1.166024
29,5.365530e+09,2.434335,0.829936,0.386175,0.272882,0.000152,0.000486,1.627701,3.207490,0.264548,...,117.148654,0.794131,0.948453,0.961435,0.789217,0.100772,0.003119,3.684076,3.005852,2.479336