In [2]:
import xarray as xr
import pandas as pd
import glob
import os
import math

import numpy as np
import re
from joblib import Parallel, delayed
from pathlib import Path
import matplotlib.pyplot as plt
import alphashape
from itertools import combinations
from collections import defaultdict, deque
from concurrent.futures import ThreadPoolExecutor
from concurrent.futures import ProcessPoolExecutor, as_completed


from shapely import points, contains
import random

In [1]:
#%pip install -e ..

In [3]:
from proj2dhullsampler import HistoryMatching

In [4]:
working_dir = '/glade/work/qingyuany/camml_re'
case_name = "test"

para = xr.open_dataset("/glade/work/qingyuany/camml_re/v0/parameter_34_100.nc")
para = para.to_dataframe().drop(columns = 'Sample_nmb')
para.index = para.index +1

In [5]:
test_case = HistoryMatching(working_dir, case_name, para, threshold_level=2.0)
test_case.drop_by_name(["TGCLDLWP", "CLDTOT"])
test_case.drop_by_n_survive(n_survive = 200000)
test_case.update_meta()

In [6]:
test_case.group_para_climatology(overlapping_threshold = 10000)
summary2d = test_case.shuffle_vars()

micro_mg_vtrmi_factor                    and micro_mg_dcs                            :        0
micro_mg_dcs                             and microp_aero_wsub_scale                  :   255301
micro_mg_dcs                             and microp_aero_wsubi_scale                 :   615788
micro_mg_vtrmi_factor                    and microp_aero_wsub_scale                  :   673309
microp_aero_wsub_scale                   and microp_aero_npccn_scale                 :     1711
micro_mg_vtrmi_factor                    and zmconv_capelmt                          :   219088
micro_mg_vtrmi_factor                    and clubb_c2rt                              :   353025
micro_mg_vtrmi_factor                    and zmconv_tiedke_add                       :   635723
micro_mg_vtrmi_factor                    and clubb_c14                               :   918002
micro_mg_vtrmi_factor                    and micro_mg_berg_eff_factor                :   954932
micro_mg_dcs                             and clubb_c1                                :   992357
There are 2 groups that have no overlapping within own groups

In [7]:
list(summary2d.values())[1]

                    var1                   var2   count
3    FSNTOA_zonal_70to75  FSNTOA_zonal_-70to-65    4509
9  FSNTOA_zonal_-75to-70  FSNTOA_zonal_-70to-65   36687
0    FSNTOA_zonal_70to75  FSNTOA_zonal_-65to-60  156042
1    FSNTOA_zonal_70to75    SWCF_zonal_-65to-60  176736
8    SWCF_zonal_-65to-60  FSNTOA_zonal_-70to-65  293257
6  FSNTOA_zonal_-65to-60  FSNTOA_zonal_-70to-65  293257
2    FSNTOA_zonal_70to75  FSNTOA_zonal_-75to-70  369007
5  FSNTOA_zonal_-65to-60  FSNTOA_zonal_-75to-70  485110
7    SWCF_zonal_-65to-60  FSNTOA_zonal_-75to-70  505991
4  FSNTOA_zonal_-65to-60    SWCF_zonal_-65to-60  777412

In [8]:
no_overlap_2d_vars = ['LWCF_zonal_-75to-70', 'FSNTOA_zonal_-70to-65']

In [9]:
test_case.drop_no_overlap2d_vars(no_overlap_2d_vars)
test_case.group_para_climatology()
summary2d = test_case.shuffle_vars()
summary2d

micro_mg_vtrmi_factor                    and micro_mg_dcs                            :    77151
micro_mg_dcs                             and microp_aero_wsub_scale                  :   255301
micro_mg_dcs                             and microp_aero_wsubi_scale                 :   615788
micro_mg_vtrmi_factor                    and microp_aero_wsub_scale                  :   673309
microp_aero_wsub_scale                   and microp_aero_npccn_scale                 :   148048
micro_mg_vtrmi_factor                    and zmconv_capelmt                          :   219088
micro_mg_vtrmi_factor                    and clubb_c2rt                              :   353025
micro_mg_vtrmi_factor                    and zmconv_tiedke_add                       :   635723
micro_mg_vtrmi_factor                    and clubb_c14                               :   918002
micro_mg_vtrmi_factor                    and micro_mg_berg_eff_factor                :   954932
micro_mg_dcs                             and clubb_c1                                :   992357
There are 0 groups that have no overlapping within own groups

{}

In [10]:
test_case.paras_vars

{('micro_mg_vtrmi_factor', 'micro_mg_dcs'): ['FLUT_zonal_45to50',
  'TMQ_zonal_-5to0',
  'PRECT_zonal_40to45',
  'FSNTOA_zonal_20to25',
  'LWCF_zonal_-70to-65',
  'FLUT_zonal_50to55',
  'FSNTOA_zonal_25to30',
  'FLUT_zonal_65to70',
  'PRECT_zonal_-15to-10',
  'LWCF_zonal_0to5',
  'LWCF_zonal_-35to-30',
  'PRECT_zonal_-45to-40',
  'FSNTOA_zonal_15to20',
  'SWCF_zonal_-25to-20',
  'LWCF_zonal_-15to-10',
  'LWCF_zonal_50to55',
  'LWCF_zonal_30to35',
  'LWCF_zonal_-45to-40',
  'PRECT_zonal_-10to-5',
  'LWCF_zonal_40to45',
  'FLUT_zonal_5to10',
  'LWCF_zonal_-5to0',
  'SWCF_zonal_-20to-15',
  'FLUT_zonal_-10to-5',
  'LWCF_zonal_-60to-55',
  'TMQ_zonal_-25to-20',
  'FLUT_zonal_-60to-55',
  'FLUT_zonal_0to5',
  'TMQ_zonal_15to20',
  'FLUT_zonal_-5to0',
  'FSNTOA_zonal_-25to-20',
  'FLUT_zonal_-75to-70',
  'TMQ_zonal_30to35',
  'FLUT_zonal_30to35',
  'TMQ_zonal_-10to-5',
  'FLUT_zonal_-55to-50',
  'TMQ_zonal_0to5',
  'PRECT_zonal_50to55',
  'TMQ_zonal_20to25',
  'FLUT_zonal_25to30',
  'FLUT_zonal_55to60',
  'FLUT_zonal_35to40',
  'PRECT_zonal_-40to-35',
  'LWCF_zonal_20to25',
  'TMQ_zonal_-20to-15',
  'FLUT_zonal_60to65',
  'FLUT_zonal_-70to-65',
  'LWCF_zonal_-10to-5',
  'FLUT_zonal_-40to-35',
  'TMQ_zonal_5to10',
  'PRECT_zonal_-50to-45',
  'LWCF_zonal_45to50',
  'LWCF_zonal_-25to-20',
  'PRECT_zonal_15to20',
  'FLUT_zonal_-20to-15',
  'LWCF_zonal_35to40',
  'PRECT_zonal_20to25',
  'LWCF_zonal_-20to-15',
  'FSNTOA_zonal_-20to-15',
  'SWCF_zonal_15to20',
  'FLUT_zonal_-15to-10',
  'FLUT_zonal_20to25',
  'LWCF_zonal_-30to-25',
  'FLUT_zonal_-45to-40',
  'LWCF_zonal_60to65',
  'PRECT_zonal_10to15',
  'LWCF_zonal_25to30',
  'FLUT_zonal_70to75',
  'LWCF_zonal_-55to-50',
  'SWCF_zonal_20to25',
  'TMQ_zonal_25to30',
  'FLUT_zonal_15to20',
  'PRECT_zonal_35to40',
  'FLUT_zonal_-35to-30',
  'LWCF_zonal_-40to-35',
  'PRECT_zonal_-35to-30',
  'FLUT_zonal_-65to-60',
  'FLUT_zonal_-25to-20',
  'SWCF_zonal_25to30',
  'LWCF_zonal_5to10',
  'LWCF_zonal_55to60',
  'LWCF_zonal_-65to-60',
  'LWCF_zonal_-50to-45',
  'LWCF_zonal_70to75',
  'FLUT_zonal_40to45',
  'PRECT_zonal_30to35',
  'TMQ_zonal_35to40',
  'PRECT_zonal_-65to-60',
  'FLUT_zonal_10to15',
  'LWCF_zonal_10to15',
  'FLUT_zonal_-30to-25',
  'LWCF_zonal_15to20',
  'PRECT_zonal_-30to-25',
  'PRECT_zonal_25to30',
  'TMQ_zonal_-15to-10',
  'PRECT_zonal_45to50',
  'TMQ_zonal_-30to-25',
  'PRECT_zonal_55to60',
  'TMQ_zonal_10to15',
  'FLUT_zonal_-50to-45',
  'LWCF_zonal_65to70'],
 ('micro_mg_dcs', 'microp_aero_wsub_scale'): ['SWCF_zonal_65to70',
  'SWCF_zonal_45to50',
  'SWCF_zonal_-60to-55',
  'FSNTOA_zonal_65to70',
  'SWCF_zonal_55to60',
  'FSNTOA_zonal_45to50',
  'FSNTOA_zonal_40to45',
  'FSNTOA_zonal_50to55',
  'SWCF_zonal_-45to-40',
  'SWCF_zonal_60to65',
  'SWCF_zonal_-50to-45',
  'SWCF_zonal_-55to-50',
  'FSNTOA_zonal_-55to-50',
  'SWCF_zonal_50to55',
  'FSNTOA_zonal_-50to-45',
  'SWCF_zonal_40to45',
  'FSNTOA_zonal_-60to-55',
  'FSNTOA_zonal_60to65',
  'FSNTOA_zonal_-45to-40',
  'FSNTOA_zonal_55to60'],
 ('micro_mg_dcs', 'microp_aero_wsubi_scale'): ['FSNTOA_zonal_0to5',
  'FSNTOA_zonal_-5to0',
  'FSNTOA_zonal_-15to-10',
  'SWCF_zonal_-15to-10',
  'FSNTOA_zonal_5to10',
  'SWCF_zonal_-10to-5',
  'SWCF_zonal_0to5',
  'SWCF_zonal_10to15',
  'SWCF_zonal_5to10',
  'FSNTOA_zonal_10to15',
  'SWCF_zonal_-5to0',
  'FSNTOA_zonal_-10to-5'],
 ('micro_mg_vtrmi_factor', 'microp_aero_wsub_scale'): ['TMQ_zonal_65to70',
  'TMQ_zonal_60to65',
  'TMQ_zonal_50to55',
  'TMQ_zonal_70to75',
  'SWCF_zonal_70to75',
  'TMQ_zonal_55to60'],
 ('microp_aero_wsub_scale', 'microp_aero_npccn_scale'): ['FSNTOA_zonal_70to75',
  'FSNTOA_zonal_-65to-60',
  'SWCF_zonal_-65to-60',
  'FSNTOA_zonal_-75to-70'],
 ('micro_mg_vtrmi_factor', 'zmconv_capelmt'): ['TMQ_zonal_-60to-55',
  'TMQ_zonal_-55to-50',
  'TMQ_zonal_-40to-35'],
 ('micro_mg_vtrmi_factor', 'clubb_c2rt'): ['TMQ_zonal_-35to-30',
  'TMQ_zonal_45to50',
  'TMQ_zonal_40to45'],
 ('micro_mg_vtrmi_factor', 'zmconv_tiedke_add'): ['PRECT_zonal_5to10',
  'PRECT_zonal_-55to-50',
  'PRECT_4_7_1_359'],
 ('micro_mg_vtrmi_factor', 'clubb_c14'): ['TMQ_zonal_-75to-70'],
 ('micro_mg_vtrmi_factor', 'micro_mg_berg_eff_factor'): ['PRECT_zonal_65to70'],
 ('micro_mg_dcs', 'clubb_c1'): ['FSNTOA_zonal_35to40']}

In [11]:
test_case.drop_by_nvar_per_pair(n_var_thre=1)

In [12]:
test_case.paras_vars

{('micro_mg_vtrmi_factor', 'micro_mg_dcs'): ['FLUT_zonal_45to50',
  'TMQ_zonal_-5to0',
  'PRECT_zonal_40to45',
  'FSNTOA_zonal_20to25',
  'LWCF_zonal_-70to-65',
  'FLUT_zonal_50to55',
  'FSNTOA_zonal_25to30',
  'FLUT_zonal_65to70',
  'PRECT_zonal_-15to-10',
  'LWCF_zonal_0to5',
  'LWCF_zonal_-35to-30',
  'PRECT_zonal_-45to-40',
  'FSNTOA_zonal_15to20',
  'SWCF_zonal_-25to-20',
  'LWCF_zonal_-15to-10',
  'LWCF_zonal_50to55',
  'LWCF_zonal_30to35',
  'LWCF_zonal_-45to-40',
  'PRECT_zonal_-10to-5',
  'LWCF_zonal_40to45',
  'FLUT_zonal_5to10',
  'LWCF_zonal_-5to0',
  'SWCF_zonal_-20to-15',
  'FLUT_zonal_-10to-5',
  'LWCF_zonal_-60to-55',
  'TMQ_zonal_-25to-20',
  'FLUT_zonal_-60to-55',
  'FLUT_zonal_0to5',
  'TMQ_zonal_15to20',
  'FLUT_zonal_-5to0',
  'FSNTOA_zonal_-25to-20',
  'FLUT_zonal_-75to-70',
  'TMQ_zonal_30to35',
  'FLUT_zonal_30to35',
  'TMQ_zonal_-10to-5',
  'FLUT_zonal_-55to-50',
  'TMQ_zonal_0to5',
  'PRECT_zonal_50to55',
  'TMQ_zonal_20to25',
  'FLUT_zonal_25to30',
  'FLUT_zonal_55to60',
  'FLUT_zonal_35to40',
  'PRECT_zonal_-40to-35',
  'LWCF_zonal_20to25',
  'TMQ_zonal_-20to-15',
  'FLUT_zonal_60to65',
  'FLUT_zonal_-70to-65',
  'LWCF_zonal_-10to-5',
  'FLUT_zonal_-40to-35',
  'TMQ_zonal_5to10',
  'PRECT_zonal_-50to-45',
  'LWCF_zonal_45to50',
  'LWCF_zonal_-25to-20',
  'PRECT_zonal_15to20',
  'FLUT_zonal_-20to-15',
  'LWCF_zonal_35to40',
  'PRECT_zonal_20to25',
  'LWCF_zonal_-20to-15',
  'FSNTOA_zonal_-20to-15',
  'SWCF_zonal_15to20',
  'FLUT_zonal_-15to-10',
  'FLUT_zonal_20to25',
  'LWCF_zonal_-30to-25',
  'FLUT_zonal_-45to-40',
  'LWCF_zonal_60to65',
  'PRECT_zonal_10to15',
  'LWCF_zonal_25to30',
  'FLUT_zonal_70to75',
  'LWCF_zonal_-55to-50',
  'SWCF_zonal_20to25',
  'TMQ_zonal_25to30',
  'FLUT_zonal_15to20',
  'PRECT_zonal_35to40',
  'FLUT_zonal_-35to-30',
  'LWCF_zonal_-40to-35',
  'PRECT_zonal_-35to-30',
  'FLUT_zonal_-65to-60',
  'FLUT_zonal_-25to-20',
  'SWCF_zonal_25to30',
  'LWCF_zonal_5to10',
  'LWCF_zonal_55to60',
  'LWCF_zonal_-65to-60',
  'LWCF_zonal_-50to-45',
  'LWCF_zonal_70to75',
  'FLUT_zonal_40to45',
  'PRECT_zonal_30to35',
  'TMQ_zonal_35to40',
  'PRECT_zonal_-65to-60',
  'FLUT_zonal_10to15',
  'LWCF_zonal_10to15',
  'FLUT_zonal_-30to-25',
  'LWCF_zonal_15to20',
  'PRECT_zonal_-30to-25',
  'PRECT_zonal_25to30',
  'TMQ_zonal_-15to-10',
  'PRECT_zonal_45to50',
  'TMQ_zonal_-30to-25',
  'PRECT_zonal_55to60',
  'TMQ_zonal_10to15',
  'FLUT_zonal_-50to-45',
  'LWCF_zonal_65to70'],
 ('micro_mg_dcs', 'microp_aero_wsub_scale'): ['SWCF_zonal_65to70',
  'SWCF_zonal_45to50',
  'SWCF_zonal_-60to-55',
  'FSNTOA_zonal_65to70',
  'SWCF_zonal_55to60',
  'FSNTOA_zonal_45to50',
  'FSNTOA_zonal_40to45',
  'FSNTOA_zonal_50to55',
  'SWCF_zonal_-45to-40',
  'SWCF_zonal_60to65',
  'SWCF_zonal_-50to-45',
  'SWCF_zonal_-55to-50',
  'FSNTOA_zonal_-55to-50',
  'SWCF_zonal_50to55',
  'FSNTOA_zonal_-50to-45',
  'SWCF_zonal_40to45',
  'FSNTOA_zonal_-60to-55',
  'FSNTOA_zonal_60to65',
  'FSNTOA_zonal_-45to-40',
  'FSNTOA_zonal_55to60'],
 ('micro_mg_dcs', 'microp_aero_wsubi_scale'): ['FSNTOA_zonal_0to5',
  'FSNTOA_zonal_-5to0',
  'FSNTOA_zonal_-15to-10',
  'SWCF_zonal_-15to-10',
  'FSNTOA_zonal_5to10',
  'SWCF_zonal_-10to-5',
  'SWCF_zonal_0to5',
  'SWCF_zonal_10to15',
  'SWCF_zonal_5to10',
  'FSNTOA_zonal_10to15',
  'SWCF_zonal_-5to0',
  'FSNTOA_zonal_-10to-5'],
 ('micro_mg_vtrmi_factor', 'microp_aero_wsub_scale'): ['TMQ_zonal_65to70',
  'TMQ_zonal_60to65',
  'TMQ_zonal_50to55',
  'TMQ_zonal_70to75',
  'SWCF_zonal_70to75',
  'TMQ_zonal_55to60'],
 ('microp_aero_wsub_scale', 'microp_aero_npccn_scale'): ['FSNTOA_zonal_70to75',
  'FSNTOA_zonal_-65to-60',
  'SWCF_zonal_-65to-60',
  'FSNTOA_zonal_-75to-70'],
 ('micro_mg_vtrmi_factor', 'zmconv_capelmt'): ['TMQ_zonal_-60to-55',
  'TMQ_zonal_-55to-50',
  'TMQ_zonal_-40to-35'],
 ('micro_mg_vtrmi_factor', 'clubb_c2rt'): ['TMQ_zonal_-35to-30',
  'TMQ_zonal_45to50',
  'TMQ_zonal_40to45'],
 ('micro_mg_vtrmi_factor', 'zmconv_tiedke_add'): ['PRECT_zonal_5to10',
  'PRECT_zonal_-55to-50',
  'PRECT_4_7_1_359']}

In [13]:
test_case.build_hulls()

In [14]:
test_case.orchestrate()

Running ('micro_mg_vtrmi_factor', 'micro_mg_dcs'), the 0th simulation
There is overlap for ('micro_mg_vtrmi_factor', 'micro_mg_dcs'). Proceed to the next parameter pair
======================================================================
Running ('micro_mg_dcs', 'microp_aero_wsub_scale'), the 1th simulation
There is overlap for ('micro_mg_dcs', 'microp_aero_wsub_scale'). Proceed to the next parameter pair
======================================================================
Running ('micro_mg_dcs', 'microp_aero_wsubi_scale'), the 2th simulation
There is overlap for ('micro_mg_dcs', 'microp_aero_wsubi_scale'). Proceed to the next parameter pair
======================================================================
Running ('micro_mg_vtrmi_factor', 'microp_aero_wsub_scale'), the 3th simulation
There is overlap for ('micro_mg_vtrmi_factor', 'microp_aero_wsub_scale'). Proceed to the next parameter pair
======================================================================
Running ('microp_aero_wsub_scale', 'microp_aero_npccn_scale'), the 4th simulation
There is overlap for ('microp_aero_wsub_scale', 'microp_aero_npccn_scale'). Proceed to the next parameter pair
======================================================================
Running ('micro_mg_vtrmi_factor', 'zmconv_capelmt'), the 5th simulation
There is overlap for ('micro_mg_vtrmi_factor', 'zmconv_capelmt'). Proceed to the next parameter pair
======================================================================
Running ('micro_mg_vtrmi_factor', 'clubb_c2rt'), the 6th simulation
There is overlap for ('micro_mg_vtrmi_factor', 'clubb_c2rt'). Proceed to the next parameter pair
======================================================================
Running ('micro_mg_vtrmi_factor', 'zmconv_tiedke_add'), the 7th simulation
There is overlap for ('micro_mg_vtrmi_factor', 'zmconv_tiedke_add'). Proceed to the next parameter pair
======================================================================

In [15]:
test_case.draw(n_pts=50000, n_threshold=5000, sample_threshold=10**6, max_workers=8, n_max=1000)

In [16]:
test_case.results.realscale_samples

,micro_mg_max_nicons,micro_mg_vtrmi_factor,micro_mg_iaccr_factor,micro_mg_berg_eff_factor,micro_mg_accre_enhan_fact,micro_mg_homog_size,micro_mg_dcs,clubb_c1,clubb_C8,clubb_c11,...,zmconv_capelmt,seasalt_emis_scale,dust_emis_fact,sol_factb_interstitial,sol_factic_interstitial,microp_aero_wsub_min,microp_aero_wsubi_min,microp_aero_wsub_scale,microp_aero_wsubi_scale,microp_aero_npccn_scale
0,5.085518e+09,3.929334,0.554600,0.574967,5.581729,0.000115,0.000408,0.687813,3.538690,0.760126,...,151.697158,1.101171,0.535446,0.719078,0.205807,0.179732,0.068041,1.938315,2.114598,0.734393
1,2.910738e+09,4.587804,0.524882,0.871795,2.203972,0.000170,0.000366,1.420181,1.099362,0.754723,...,66.829103,2.134961,0.111655,0.997026,0.300330,0.189593,0.148207,1.288124,2.743740,2.567392
2,8.435482e+08,4.872675,0.321374,0.816359,1.619403,0.000013,0.000315,2.954336,4.793016,0.400098,...,135.174083,2.398829,0.147599,0.120803,0.939548,0.495290,0.174523,1.524380,2.856169,2.075626
3,4.944764e+09,3.106683,0.458829,0.860387,8.436325,0.000198,0.000340,0.482575,1.736848,0.330456,...,94.633055,0.899453,0.450598,0.683760,0.879237,0.236894,0.097357,1.074611,0.816518,1.393446
4,1.442921e+09,4.741596,0.575197,0.327953,3.237176,0.000084,0.000440,2.534740,4.830674,0.395294,...,80.715191,0.752088,0.735733,0.142311,0.807701,0.085235,0.187971,1.412915,1.643700,2.739248
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,9.895705e+09,4.587014,0.345735,0.508833,0.429077,0.000063,0.000533,0.721955,2.786986,0.321454,...,128.668990,1.995702,0.706025,0.671388,0.560022,0.147824,0.021455,1.366969,0.431769,2.440874
942,4.638879e+09,4.680991,0.571665,0.464321,3.781759,0.000073,0.000355,0.754171,2.745752,0.636984,...,85.539149,1.365807,0.597398,0.736789,0.954071,0.248569,0.053716,1.418162,2.971545,1.817906
943,7.692298e+09,4.545168,0.876568,0.493333,2.641149,0.000133,0.000590,1.077543,1.217596,0.704410,...,40.098753,1.223045,0.787474,0.316162,0.757148,0.110441,0.091608,1.099264,1.902816,1.246269
944,2.192113e+09,4.755167,0.727224,0.797386,1.807451,0.000178,0.000508,0.780982,4.168354,0.606373,...,115.449873,0.905721,0.694295,0.236212,0.204975,0.092672,0.067398,0.939348,1.841113,1.560875
945,8.349482e+09,4.594203,0.785744,0.601660,3.898950,0.000073,0.000341,1.302144,3.432431,0.545672,...,90.260608,2.277628,0.301490,0.384051,0.953416,0.281146,0.091222,1.625476,2.591186,0.596428

In [17]:

#plot_histograms_grid_5([para, test_case.results.realscale_samples])

In [18]:
test_case.save_samples(n = 100)

(946, 34)
['001', '002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012', '013', '014', '015', '016', '017', '018', '019', '020', '021', '022', '023', '024', '025', '026', '027', '028', '029', '030', '031', '032', '033', '034', '035', '036', '037', '038', '039', '040', '041', '042', '043', '044', '045', '046', '047', '048', '049', '050', '051', '052', '053', '054', '055', '056', '057', '058', '059', '060', '061', '062', '063', '064', '065', '066', '067', '068', '069', '070', '071', '072', '073', '074', '075', '076', '077', '078', '079', '080', '081', '082', '083', '084', '085', '086', '087', '088', '089', '090', '091', '092', '093', '094', '095', '096', '097', '098', '099', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', '256', '257', '258', '259', '260', '261', '262', '263', '264', '265', '266', '267', '268', '269', '270', '271', '272', '273', '274', '275', '276', '277', '278', '279', '280', '281', '282', '283', '284', '285', '286', '287', '288', '289', '290', '291', '292', '293', '294', '295', '296', '297', '298', '299', '300', '301', '302', '303', '304', '305', '306', '307', '308', '309', '310', '311', '312', '313', '314', '315', '316', '317', '318', '319', '320', '321', '322', '323', '324', '325', '326', '327', '328', '329', '330', '331', '332', '333', '334', '335', '336', '337', '338', '339', '340', '341', '342', '343', '344', '345', '346', '347', '348', '349', '350', '351', '352', '353', '354', '355', '356', '357', '358', '359', '360', '361', '362', '363', '364', '365', '366', '367', '368', '369', '370', '371', '372', '373', '374', '375', '376', '377', '378', '379', '380', '381', '382', '383', '384', '385', '386', '387', '388', '389', '390', '391', '392', '393', '394', '395', '396', '397', '398', '399', '400', '401', '402', '403', '404', '405', '406', '407', '408', '409', '410', '411', '412', '413', '414', '415', '416', '417', '418', '419', '420', '421', '422', '423', '424', '425', '426', '427', '428', '429', '430', '431', '432', '433', '434', '435', '436', '437', '438', '439', '440', '441', '442', '443', '444', '445', '446', '447', '448', '449', '450', '451', '452', '453', '454', '455', '456', '457', '458', '459', '460', '461', '462', '463', '464', '465', '466', '467', '468', '469', '470', '471', '472', '473', '474', '475', '476', '477', '478', '479', '480', '481', '482', '483', '484', '485', '486', '487', '488', '489', '490', '491', '492', '493', '494', '495', '496', '497', '498', '499', '500', '501', '502', '503', '504', '505', '506', '507', '508', '509', '510', '511', '512', '513', '514', '515', '516', '517', '518', '519', '520', '521', '522', '523', '524', '525', '526', '527', '528', '529', '530', '531', '532', '533', '534', '535', '536', '537', '538', '539', '540', '541', '542', '543', '544', '545', '546', '547', '548', '549', '550', '551', '552', '553', '554', '555', '556', '557', '558', '559', '560', '561', '562', '563', '564', '565', '566', '567', '568', '569', '570', '571', '572', '573', '574', '575', '576', '577', '578', '579', '580', '581', '582', '583', '584', '585', '586', '587', '588', '589', '590', '591', '592', '593', '594', '595', '596', '597', '598', '599', '600', '601', '602', '603', '604', '605', '606', '607', '608', '609', '610', '611', '612', '613', '614', '615', '616', '617', '618', '619', '620', '621', '622', '623', '624', '625', '626', '627', '628', '629', '630', '631', '632', '633', '634', '635', '636', '637', '638', '639', '640', '641', '642', '643', '644', '645', '646', '647', '648', '649', '650', '651', '652', '653', '654', '655', '656', '657', '658', '659', '660', '661', '662', '663', '664', '665', '666', '667', '668', '669', '670', '671', '672', '673', '674', '675', '676', '677', '678', '679', '680', '681', '682', '683', '684', '685', '686', '687', '688', '689', '690', '691', '692', '693', '694', '695', '696', '697', '698', '699', '700', '701', '702', '703', '704', '705', '706', '707', '708', '709', '710', '711', '712', '713', '714', '715', '716', '717', '718', '719', '720', '721', '722', '723', '724', '725', '726', '727', '728', '729', '730', '731', '732', '733', '734', '735', '736', '737', '738', '739', '740', '741', '742', '743', '744', '745', '746', '747', '748', '749', '750', '751', '752', '753', '754', '755', '756', '757', '758', '759', '760', '761', '762', '763', '764', '765', '766', '767', '768', '769', '770', '771', '772', '773', '774', '775', '776', '777', '778', '779', '780', '781', '782', '783', '784', '785', '786', '787', '788', '789', '790', '791', '792', '793', '794', '795', '796', '797', '798', '799', '800', '801', '802', '803', '804', '805', '806', '807', '808', '809', '810', '811', '812', '813', '814', '815', '816', '817', '818', '819', '820', '821', '822', '823', '824', '825', '826', '827', '828', '829', '830', '831', '832', '833', '834', '835', '836', '837', '838', '839', '840', '841', '842', '843', '844', '845', '846', '847', '848', '849', '850', '851', '852', '853', '854', '855', '856', '857', '858', '859', '860', '861', '862', '863', '864', '865', '866', '867', '868', '869', '870', '871', '872', '873', '874', '875', '876', '877', '878', '879', '880', '881', '882', '883', '884', '885', '886', '887', '888', '889', '890', '891', '892', '893', '894', '895', '896', '897', '898', '899', '900', '901', '902', '903', '904', '905', '906', '907', '908', '909', '910', '911', '912', '913', '914', '915', '916', '917', '918', '919', '920', '921', '922', '923', '924', '925', '926', '927', '928', '929', '930', '931', '932', '933', '934', '935', '936', '937', '938', '939', '940', '941', '942', '943', '944', '945', '946']
<class 'numpy.ndarray'>
<class 'list'>
(100, 34)
['001', '002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012', '013', '014', '015', '016', '017', '018', '019', '020', '021', '022', '023', '024', '025', '026', '027', '028', '029', '030', '031', '032', '033', '034', '035', '036', '037', '038', '039', '040', '041', '042', '043', '044', '045', '046', '047', '048', '049', '050', '051', '052', '053', '054', '055', '056', '057', '058', '059', '060', '061', '062', '063', '064', '065', '066', '067', '068', '069', '070', '071', '072', '073', '074', '075', '076', '077', '078', '079', '080', '081', '082', '083', '084', '085', '086', '087', '088', '089', '090', '091', '092', '093', '094', '095', '096', '097', '098', '099', '100']
<class 'numpy.ndarray'>
<class 'list'>

In [19]:
test_case.write_specifications()